# Generated by Django 4.0.6 on 2022-09-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_step',
            new_name='preparation_steps',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_step_is_html',
            new_name='preparation_steps_is_html',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='serving',
            new_name='servings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='serving_unit',
            new_name='servings_unit',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='uptade_at',
            new_name='updated_at',
        ),
    ]
